repos:
  - repo: https://github.com/golangci/golangci-lint
    rev: v1.63.4
    hooks:
      - id: golangci-lint
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: check-json
      - id: check-yaml
      - id: check-added-large-files
      - id: check-toml
      - id: detect-private-key
      - id: mixed-line-ending
      - id: no-commit-to-branch
        args: [-b, main]
      - id: trailing-whitespace
        args: [--markdown-linebreak-ext=md]
